# Generated by Django 5.1.1 on 2024-10-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_products_kasmetika'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kasmetika',
            name='img',
        ),
    ]
